/**
 * @file nvcc_wrapper.h
 * @brief NVCC compiler wrapper for SafeCUDA PTX modification pipeline
 *
 * Provides functionality to intercept NVCC compilation, generate PTX,
 * coordinate PTX modification, and resume compilation from modified PTX.
 *
 * @author Kiran <kiran.pdas2022@vitstudent.ac.in>
 * @date 2025-08-12
 * @version 0.0.1
 * @copyright Copyright (c) 2025 SafeCUDA Project. Licensed under GPL v3.
 *
 * Change Log:
 * - 2025-08-12: Initial File
 */

#ifndef SAFECUDA_NVCC_WRAPPER_H
#define SAFECUDA_NVCC_WRAPPER_H

#include <vector>
#include <string>

namespace safecuda::tools::sf_nvcc
{
/**
 * @brief Generate PTX files using nvcc
 *
 * Runs NVCC with --keep to generate ptx files
 *
 * @param nvcc_args List of arguments to be passed to nvcc
 * @return List of paths of intermediate file generated by nvcc
 */
std::vector<std::string>
generate_ptx(const std::vector<std::string> &nvcc_args);

/**
 * @brief Insert guards to generated PTX files
 *
 * Perform parsing PTX assembly, identifying memory operations,
 * and injecting bounds checking macros into load/store instructions.
 *
 * @param ptx_paths List of paths for ptx files to be modified
 * @return List of modifications done by the function for logging purposes
 */
std::vector<std::string> modify_ptx(const std::vector<std::string> &ptx_paths);

/**
 * @brief Resume compilation with nvcc on intermediate files
 *
 * Call nvcc again on files generated on nvcc --keep to continue compilation
 *
 * @param intermediate_paths List of paths of all intermediate nvcc files
 */
void resume_nvcc(const std::vector<std::string> &intermediate_paths);

} // namespace safecuda::tools::sf_nvcc

#endif // SAFECUDA_NVCC_WRAPPER_H
